import images from "./images";

export const BooksForSale = [
  {
    id: 1,
    Name: "CSC 101",
    Author: "Unknown",
    Desc: "It is 1939. Nazi Germany. The country is holidng its breath. Death has never been busier, and will be busier still. It is 1939. Nazi Germany. The country is holidng its breath. Death has never been busier, and will be busier still.",
    Price: "1500",
    image: images.csc101,
  },
  {
    id: 2,
    Name: "CSC 102",
    Author: "Unknown",
    Desc: "It is 1939. Nazi Germany. The country is holidng its breath. Death has never been busier, and will be busier still. It is 1939. Nazi Germany. The country is holidng its breath. Death has never been busier, and will be busier still.",
    Price: "1500",
    image: images.csc102,
  },
  {
    id: 3,
    Name: "CSC 201",
    Author: "Unknown",
    Desc: "It is 1939. Nazi Germany. The country is holidng its breath. Death has never been busier, and will be busier still. It is 1939. Nazi Germany. The country is holidng its breath. Death has never been busier, and will be busier still.",
    Price: "1500",
    image: images.cscCover,
  },
  {
    id: 4,
    Name: "CSC 202",
    Author: "Unknown",
    Desc: "It is 1939. Nazi Germany. The country is holidng its breath. Death has never been busier, and will be busier still. It is 1939. Nazi Germany. The country is holidng its breath. Death has never been busier, and will be busier still.",
    Price: "1500",
    image: images.cscCover,
  },
  {
    id: 5,
    Name: "CSC 301",
    Author: "Unknown",
    Desc: "It is 1939. Nazi Germany. The country is holidng its breath. Death has never been busier, and will be busier still. It is 1939. Nazi Germany. The country is holidng its breath. Death has never been busier, and will be busier still.",
    Price: "1500",
    image: images.cscCover,
  },
  {
    id: 6,
    Name: "CSC 401",
    Author: "Unknown",
    Desc: "It is 1939. Nazi Germany. The country is holidng its breath. Death has never been busier, and will be busier still. It is 1939. Nazi Germany. The country is holidng its breath. Death has never been busier, and will be busier still.",
    Price: "1500",
    image: images.cscCover,
  },
  {
    id: 7,
    Name: "CSC 402",
    Author: "Unknown",
    Desc: "It is 1939. Nazi Germany. The country is holidng its breath. Death has never been busier, and will be busier still. It is 1939. Nazi Germany. The country is holidng its breath. Death has never been busier, and will be busier still.",
    Price: "1500",
    image: images.cscCover,
  },
  {
    id: 8,
    Name: "CSC 311",
    Author: "Unknown",
    Desc: "It is 1939. Nazi Germany. The country is holidng its breath. Death has never been busier, and will be busier still. It is 1939. Nazi Germany. The country is holidng its breath. Death has never been busier, and will be busier still.",
    Price: "1500",
    image: images.cscCover,
  },
  {
    id: 9,
    Name: "CSC 212",
    Author: "Unknown",
    Desc: "It is 1939. Nazi Germany. The country is holidng its breath. Death has never been busier, and will be busier still. It is 1939. Nazi Germany. The country is holidng its breath. Death has never been busier, and will be busier still.",
    Price: "1500",
    image: images.cscCover,
  },
  {
    id: 10,
    Name: "CSC 206",
    Author: "Unknown",
    Desc: "It is 1939. Nazi Germany. The country is holidng its breath. Death has never been busier, and will be busier still. It is 1939. Nazi Germany. The country is holidng its breath. Death has never been busier, and will be busier still.",
    Price: "1500",
    image: images.cscCover,
  },
  {
    id: 11,
    Name: "CSC 421",
    Author: "Unknown",
    Desc: "It is 1939. Nazi Germany. The country is holidng its breath. Death has never been busier, and will be busier still. It is 1939. Nazi Germany. The country is holidng its breath. Death has never been busier, and will be busier still.",
    Price: "1500",
    image: images.cscCover,
  },
];
